training_dir: "/home/nauck/joined_work/landscape_generation/ml_training/run_ns20_ds20_TAG"
dataset_root_path: "/home/nauck/joined_work/landscape_generation/datasets/root_path"
batch_size: 32
learning_rate: 7.767159217026848e-05
num_epochs: 250
eval_interval: 10
train_slice_index: [1, 7000]
val_slice_index: [7001, 8500]
test_slice_index: [8501, 10000]
dataset_name: "ds20"
num_sections: 20
manual_seed: 1
