gnn_dropout_rate: 0.1483745044419462
gnn_hidden_channels: 1751
gnn_in_channels: 1
gnn_layer_type: TAGConv
gnn_num_layers: 5
gnn_out_channels: 671
image_size: 20
mlp_dropout: 0.26
mlp_hidden_channels: 654
mlp_out_channels: 512
